ARG UBUNTU_VERSION
FROM --platform=${BUILDPLATFORM} ubuntu:${UBUNTU_VERSION}

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get -y install ca-certificates curl gnupg lsb-release
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
RUN echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN apt-get update --fix-missing
RUN apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
RUN apt-get install -y git bash make curl wget vim

# Install console dependencies
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get update
RUN apt-get install -y nodejs

RUN rm -rf /var/lib/apt/lists/*

# Install k6
ARG TARGETARCH K6_VERSION
ADD https://github.com/grafana/k6/releases/download/v${K6_VERSION}/k6-v${K6_VERSION}-linux-$TARGETARCH.tar.gz k6-v${K6_VERSION}-linux-$TARGETARCH.tar.gz
RUN tar -xf k6-v${K6_VERSION}-linux-$TARGETARCH.tar.gz --strip-components 1 -C /usr/bin

COPY --from=docker:dind /usr/local/bin/docker /usr/local/bin/

WORKDIR /vdp/dev

ARG PROFILE
RUN if [ "${PROFILE}" = "all" ] || [ "${PROFILE}" = "api-gateway" ]; then git clone https://github.com/instill-ai/api-gateway.git api-gateway; fi
RUN if [ "${PROFILE}" = "all" ] || [ "${PROFILE}" = "pipeline" ]; then git clone https://github.com/instill-ai/pipeline-backend.git pipeline-backend; fi
RUN if [ "${PROFILE}" = "all" ] || [ "${PROFILE}" = "connector" ]; then git clone https://github.com/instill-ai/connector-backend.git connector-backend; fi
RUN if [ "${PROFILE}" = "all" ] || [ "${PROFILE}" = "model" ]; then git clone https://github.com/instill-ai/model-backend.git model-backend; fi
RUN if [ "${PROFILE}" = "all" ] || [ "${PROFILE}" = "mgmt" ]; then git clone https://github.com/instill-ai/mgmt-backend.git mgmt-backend; fi
RUN if [ "${PROFILE}" = "all" ] || [ "${PROFILE}" = "console" ]; then git clone https://github.com/instill-ai/console.git console; fi
