%%{
  init: {
    'themeVariables': {
      'primaryBorderColor': '#1A1A1A',
      'secondaryBorderColor': '#1A1A1A',
      'tertiaryBorderColor': '#1A1A1A',
      'lineColor': '#1A1A1A',
      'actorBkg': '#80A8F5',
      'actorBorder': '#1A1A1A',
      'actorTextColor': '#1A1A1A',
      'actorLineColor': '#1A1A1A',
      'noteBkgColor': '#FFDF3A',
      'noteBorderColor': '#1A1A1A',
      'noteTextColor': '#1A1A1A',
      'activationBkgColor': '#28F67E',
      'activationBorderColor': '#1A1A1A',
      'sequenceNumberColor': '#FFFFFF',
      'textColor': '#1A1A1A'
    },
    'themeCSS': 'background-color: white;'
  }
}%%
sequenceDiagram
  participant Users
  autonumber
  Note right of Users: Triggering<br>Pipeline
  Users->>+Pipeline: HTTP/gRPC
  Pipeline->>-Users: HTTP/gRPC (Ack)
  Pipeline-->>+Model: Predict<br>Request
  Model-->>-Pipeline: Result
  Pipeline-->>PostgreSQL: Insert/Update result
  Users->>PostgreSQL: Query result
